version: '3.8'
# todo: test this one
services:
  # application services
  web_app:
    build: winterrdog/blog-api:1.3.6
    container_name: blog_backend
    ports:
      - "3000:3000"
    networks:
      - mongo_network
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    env_file:
      - ./.env
    volumes:
      - ./:/var/log:rw
  # database services
  mongo1:
    image: mongo:8.0.0-rc16-jammy
    container_name: mongo1
    networks:
      - mongo_network
    ports:
      - "27015:27017"
    command: bash -c "mongod --replSet rs0 --bind_ip_all && sleep 4 && /scripts/init-replica-sets.sh"
    volumes:
      - mongo1_data:/data/db:rw
      - ./scripts:/scripts:ro
  mongo2:
    image: mongo:8.0.0-rc16-jammy
    container_name: mongo2
    networks:
      - mongo_network
    ports:
      - "27018:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo2_data:/data/db:rw
  mongo3:
    image: mongo:8.0.0-rc16-jammy
    container_name: mongo3
    networks:
      - mongo_network
    ports:
      - "27019:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo3_data:/data/db:rw

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo1_data:
    driver: local
  mongo2_data:
    driver: local
  mongo3_data:
    driver: local
