services:
  # application services
  web_app:
    image: winterrdog/blog-api:1.3.6
    container_name: blog_backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/var/log:rw
